
/**
 * OOPSBannerApp UC1 – OOPS Banner Display Application
 *
 * This class demonstrates a simple Java application that displays the Object
 * Oriented Programming System OOPS acronym to the console.
 *
 * @author Developer
 * @version 1.0
 */

/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.</p>
 *
 * @author Developer
 * @version 2
 *
 */
/**
 * OOPSBannerApp UC3 – OOPS Banner Application (Use Case 3)
 *
 * This class extends the functionality of Use Case 2 by improving the way the "OOPS" banner
 * is constructed and displayed. It focuses on enhancing code readability and efficiency
 * by utilizing the String.join() method to create each line of the banner. This approach
 * overcomes the drawbacks of using the + operator for string concatenation, which can lead
 * to code inefficiency due to the creation of multiple intermediate String objects in memory.
 *
 * @author Developer
 * @version 3.0
 */
/**
 * OOPSBannerApp UC4 – Render OOPS as Banner using String Array and Loop
 *
 * This use case improves upon UC3 by using a String array to store banner lines
 * and iterating through them with a for-each loop, eliminating hardcoded print
 * statements and improving modularity and reusability.
 *
 * @author Developer
 * @version 4
 */
/**
 * OOPSBannerApp UC5 – Render OOPS as Banner using Inline Array Initialization
 *
 * This use case extends UC4 by defining and populating the String array in a more
 * concise way at the time of declaration using String.join() method to create each
 * line for the banner. This further enhances code readability and maintainability.
 *
 * @author Developer
 * @version 5.0
 */
public class Main
{
    public static void main(String[] args){
        //UC1
        System.out.println("OOPS");

        //UC2
        // Main method to run the banner display
        // Print each line of the OOPS banner to create the visual effect for the
        // message "OOPS". Construct each line using string concatenation.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        // Using individual print statements for each line.
        System.out.println("   ***   " + " " + "   ***   " + " " + "******  " + " " + "   *****");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + " **   ");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + "**   ");
        System.out.println("**     **" + " " + "**     **" + " " + "******" +   " " + "    ***");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     " + "      ** ");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     "+  "      **");
        System.out.println("   ***   " + " " + "   ***   " + " " + "**" +   "      " + "*****   ");

        //UC3
        // Construct each line using String.join() method for better readability and efficiency.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        System.out.println(String.join(" ", "   ***   ","   ***   ","******  ","   *****"));
        System.out.println(String.join(" ","**     **","**     **","**    **"," **   "));
        System.out.println(String.join(" ","**     **","**     **","**    **","**   "));
        System.out.println(String.join(" ","**     **","**     **","******","    ***"));
        System.out.println(String.join(" ","**     **","**     **","**","           ** "));
        System.out.println(String.join(" ","**     **","**     **","**","             **"));
        System.out.println(String.join(" ","   ***   ","   ***   ","**","       *****   "));


        //UC4
        // Extend the user story 3 to further develop the OOPS Banner Application
        // by using String arrays to hold banner lines and printing them in a loop.
        // This use case improves upon UC3 by using a String array to store banner lines
        // and iterating through them with a for-each loop, eliminating hardcoded print
        // statements and improving modularity and reusability.
        String[] lines = new String[7];
        lines[0] = String.join(" ", "   ***   ","   ***   ","******  ","   *****");
        lines[1] = String.join(" ","**     **","**     **","**    **"," **   ");
        lines[2] = String.join(" ","**     **","**     **","**    **","**   ");
        lines[3] = String.join(" ","**     **","**     **","******","    ***");
        lines[4] = String.join(" ","**     **","**     **","**","           ** ");
        lines[5] = String.join(" ","**     **","**     **","**","             **");
        lines[6] = String.join(" ","   ***   ","   ***   ","**","       *****   ");

        for(String line : lines){
            System.out.println(line);
        }

        //UC5
        // Extend the user story 4 to further develop the OOPS Banner Application by
        // only using String arrays to hold banner lines and printing them in a
        // loop. But also by defining and populating the array in a more concise way
        // at the time of declaration using String.join() method to create each line
        // of the banner.
        String[] lines1 = {
                String.join(" ", "   ***   ","   ***   ","******  ","   *****"),
                String.join(" ","**     **","**     **","**    **"," **   "),
                String.join(" ","**     **","**     **","**    **","**   "),
                String.join(" ","**     **","**     **","******","    ***"),
                String.join(" ","**     **","**     **","**","           ** "),
                String.join(" ","**     **","**     **","**","             **"),
                String.join(" ","   ***   ","   ***   ","**","       *****   ")
        };
        for(String line : lines1){
            System.out.println(line);
        }

    }
}
