
/**
 * OOPSBannerApp UC1 – OOPS Banner Display Application
 *
 * This class demonstrates a simple Java application that displays the Object
 * Oriented Programming System OOPS acronym to the console.
 *
 * @author Developer
 * @version 1.0
 */

/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.</p>
 *
 * @author Developer
 * @version 2
 *
 */
/**
 * OOPSBannerApp UC3 – OOPS Banner Application (Use Case 3)
 *
 * This class extends the functionality of Use Case 2 by improving the way the "OOPS" banner
 * is constructed and displayed. It focuses on enhancing code readability and efficiency
 * by utilizing the String.join() method to create each line of the banner. This approach
 * overcomes the drawbacks of using the + operator for string concatenation, which can lead
 * to code inefficiency due to the creation of multiple intermediate String objects in memory.
 *
 * @author Developer
 * @version 3.0
 */

public class Main
{
    public static void main(String[] args){
        System.out.println("OOPS");

        // Main method to run the banner display
        // Print each line of the OOPS banner to create the visual effect for the
        // message "OOPS". Construct each line using string concatenation.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        // Using individual print statements for each line.
        System.out.println("   ***   " + " " + "   ***   " + " " + "******  " + " " + "   *****");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + " **   ");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + "**   ");
        System.out.println("**     **" + " " + "**     **" + " " + "******" +   " " + "    ***");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     " + "      ** ");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     "+  "      **");
        System.out.println("   ***   " + " " + "   ***   " + " " + "**" +   "      " + "*****   ");

        // Construct each line using String.join() method for better readability and efficiency.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        System.out.println(String.join(" ", "   ***   ","   ***   ","******  ","   *****"));
        System.out.println(String.join(" ","**     **","**     **","**    **"," **   "));
        System.out.println(String.join(" ","**     **","**     **","**    **","**   "));
        System.out.println(String.join(" ","**     **","**     **","******","    ***"));
        System.out.println(String.join(" ","**     **","**     **","**","           ** "));
        System.out.println(String.join(" ","**     **","**     **","**","             **"));
        System.out.println(String.join(" ","   ***   ","   ***   ","**","       *****   "));

    }
}
