
/**
 * OOPSBannerApp UC1 – OOPS Banner Display Application
 *
 * This class demonstrates a simple Java application that displays the Object
 * Oriented Programming System OOPS acronym to the console.
 *
 * @author Developer
 * @version 1.0
 */

/**
 * OOPSBannerApp UC2 – Banner Display Application
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.</p>
 *
 * @author Developer
 * @version 2
 *
 */
/**
 * OOPSBannerApp UC3 – OOPS Banner Application (Use Case 3)
 *
 * This class extends the functionality of Use Case 2 by improving the way the "OOPS" banner
 * is constructed and displayed. It focuses on enhancing code readability and efficiency
 * by utilizing the String.join() method to create each line of the banner. This approach
 * overcomes the drawbacks of using the + operator for string concatenation, which can lead
 * to code inefficiency due to the creation of multiple intermediate String objects in memory.
 *
 * @author Developer
 * @version 3.0
 */
/**
 * OOPSBannerApp UC4 – Render OOPS as Banner using String Array and Loop
 *
 * This use case improves upon UC3 by using a String array to store banner lines
 * and iterating through them with a for-each loop, eliminating hardcoded print
 * statements and improving modularity and reusability.
 *
 * @author Developer
 * @version 4
 */
/**
 * OOPSBannerApp UC5 – Render OOPS as Banner using Inline Array Initialization
 *
 * This use case extends UC4 by defining and populating the String array in a more
 * concise way at the time of declaration using String.join() method to create each
 * line for the banner. This further enhances code readability and maintainability.
 *
 * @author Developer
 * @version 5.0
 */
 /**
 * OOPSBannerApp UC6 – OOPS Banner Application (Use Case 6)
 *
 * This use case extends UC5 by implementing a modular approach to generate each
 * letter's pattern through dedicated methods. This enhances code reusability and
 * maintainability by separating pattern generation logic from the main display logic.
 *
 * @author Developer
 * @version 6.0
 */
/**
 * OOPSBannerApp UC7 - Store Character Pattern using Inner Static Class
 *
 * This application prints the banner for the word "OOPS" by storing
 * character patterns using an inner static class and displaying them
 * using StringBuilder for efficient concatenation.
 *
 * @author Developer
 * @version 7.0
 */
import java.util.HashMap;
import java.util.Map;

/**
 * UC8 – Banner printing using HashMap and utility methods
 * Prints the word "OOPS" using ASCII patterns.
 */

public class Main
{
    public static void main(String[] args){
        //UC1
        System.out.println("-----UC1-----");
        System.out.println("OOPS");
        System.out.println("-----UC2-----");

        //UC2
        // Main method to run the banner display
        // Print each line of the OOPS banner to create the visual effect for the
        // message "OOPS". Construct each line using string concatenation.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        // Using individual print statements for each line.
        System.out.println("   ***   " + " " + "   ***   " + " " + "******  " + " " + "   *****");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + " **   ");
        System.out.println("**     **" + " " + "**     **" + " " + "**    **" + " " + "**   ");
        System.out.println("**     **" + " " + "**     **" + " " + "******" +   " " + "    ***");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     " + "      ** ");
        System.out.println("**     **" + " " + "**     **" + " " + "**" +       "     "+  "      **");
        System.out.println("   ***   " + " " + "   ***   " + " " + "**" +   "      " + "*****   ");

        System.out.println("-----UC3-----");

        //UC3
        // Construct each line using String.join() method for better readability and efficiency.
        // Each line corresponds to a row in the banner for the letters O, O, P, S.
        System.out.println(String.join(" ", "   ***   ","   ***   ","******  ","   *****"));
        System.out.println(String.join(" ","**     **","**     **","**    **"," **   "));
        System.out.println(String.join(" ","**     **","**     **","**    **","**   "));
        System.out.println(String.join(" ","**     **","**     **","******","    ***"));
        System.out.println(String.join(" ","**     **","**     **","**","           ** "));
        System.out.println(String.join(" ","**     **","**     **","**","             **"));
        System.out.println(String.join(" ","   ***   ","   ***   ","**","       *****   "));


        //UC4
        // Extend the user story 3 to further develop the OOPS Banner Application
        // by using String arrays to hold banner lines and printing them in a loop.
        // This use case improves upon UC3 by using a String array to store banner lines
        // and iterating through them with a for-each loop, eliminating hardcoded print
        // statements and improving modularity and reusability.
        String[] lines = new String[7];
        lines[0] = String.join(" ", "   ***   ","   ***   ","******  ","   *****");
        lines[1] = String.join(" ","**     **","**     **","**    **"," **   ");
        lines[2] = String.join(" ","**     **","**     **","**    **","**   ");
        lines[3] = String.join(" ","**     **","**     **","******","    ***");
        lines[4] = String.join(" ","**     **","**     **","**","           ** ");
        lines[5] = String.join(" ","**     **","**     **","**","             **");
        lines[6] = String.join(" ","   ***   ","   ***   ","**","       *****   ");

        System.out.println("-----UC4-----");

        for(String line : lines){
            System.out.println(line);
        }

        //UC5
        // Extend the user story 4 to further develop the OOPS Banner Application by
        // only using String arrays to hold banner lines and printing them in a
        // loop. But also by defining and populating the array in a more concise way
        // at the time of declaration using String.join() method to create each line
        // of the banner.
        String[] lines1 = {
                String.join(" ", "   ***   ","   ***   ","******  ","   *****"),
                String.join(" ","**     **","**     **","**    **"," **   "),
                String.join(" ","**     **","**     **","**    **","**   "),
                String.join(" ","**     **","**     **","******","    ***"),
                String.join(" ","**     **","**     **","**","           ** "),
                String.join(" ","**     **","**     **","**","             **"),
                String.join(" ","   ***   ","   ***   ","**","       *****   ")
        };
        System.out.println("-----UC5-----");
        for(String line : lines1){
            System.out.println(line);
        }

        //UC6
        // Extend the User Story 5 to display the OOPS banner using a modular approach
        //Declare String Arrays to hold the Patterns for each letter
        String[] oPattern = getOPattern();
        String[] pPattern = getPPattern();
        String[] sPattern = getSPattern();
        //Use the loop to Assemble each line of the banner to create
        // the visual effect for the message 'OOPS'
        System.out.println("-----UC6-----");
        for(int i=0; i<oPattern.length; i++){
            System.out.println(oPattern[i]+ " "+oPattern[i]+" "+ pPattern[i]+" "+sPattern[i]);
        }
        //UC7
        CharacterPatternMap[] patterns = new CharacterPatternMap[] {

                new CharacterPatternMap('O', new String[] {
                        "   ***   ",
                        "**     **",
                        "**     **",
                        "**     **",
                        "**     **",
                        "**     **",
                        "   ***   "
                }),

                new CharacterPatternMap('O', new String[] {
                        "   ***   ",
                        "**     **",
                        "**     **",
                        "**     **",
                        "**     **",
                        "**     **",
                        "   ***   "
                }),

                new CharacterPatternMap('P', new String[] {
                        "******  ",
                        "**    **",
                        "**    **",
                        "******",
                        "**",
                        "**",
                        "**",
                }),

                new CharacterPatternMap('S', new String[] {
                        "   *****",
                        " **   ",
                        "**   ",
                        "    ***",
                        "           ** ",
                        "             **",
                        "       *****   "
                })
        };
        int rows = patterns[0].getCharacterPattern().length;
        System.out.println("-----UC7-----");
        for (int i = 0; i < rows; i++) {

            StringBuilder line = new StringBuilder();

            for (CharacterPatternMap map : patterns) {
                line.append(map.getCharacterPattern()[i]).append(" ");
            }

            System.out.println(line.toString());
        }
        //UC8
        System.out.println("-----UC8-----");
        displayBanner("OOPS");
    }

    // Method to generate the pattern for the letter 'O'
    public static String[] getOPattern(){
        return new String[] {
                "   ***   ",
                "**     **",
                "**     **",
                "**     **",
                "**     **",
                "**     **",
                "   ***   "
        };
    }
    // Method to generate the pattern for the letter 'P'
    public static  String[] getPPattern(){
        return new String[] {
                "******  ",
                "**    **",
                "**    **",
                "******",
                "**",
                "**",
                "**",
        };
    }
    // Method to generate the pattern for the letter 'S'
    public static String[] getSPattern() {
        return new String[]{
                "   *****",
                " **   ",
                "**   ",
                "    ***",
                "           ** ",
                "             **",
                "       *****   "
        };
    }
        //UC7
        /**
         * Inner static class used to store a character and its banner pattern.
         * This class encapsulates the character and its corresponding pattern.
         */
        public static class CharacterPatternMap {

            private final char character;
            private final String[] pattern;
            /**
             * Constructor to initialize character and its pattern.
             * @param character the character to be displayed
             * @param pattern   the banner pattern of the character
             */
            public CharacterPatternMap(char character, String[] pattern) {
                this.character = character;
                this.pattern = pattern;
            }
            /**
             * Returns the character.
             * @return the character
             */
            public char getCharacter() {
                return character;
            }
            /**
             * Returns the banner pattern for the character.
             * @return the pattern of the character
             */
            public String[] getCharacterPattern() {
                return pattern;
            }
        }
    //UC8
    public static Map<Character, String[]> buildCharacterPatternMap() {

        Map<Character, String[]> patternMap = new HashMap<>();

        patternMap.put('O', new String[]{
                "   ***   ",
                "**     **",
                "**     **",
                "**     **",
                "**     **",
                "**     **",
                "   ***   "
        });

        patternMap.put('P', new String[]{
                "******  ",
                "**    **",
                "**    **",
                "******",
                "**",
                "**",
                "**",
        });

        patternMap.put('S', new String[]{
                "   *****",
                " **   ",
                "**   ",
                "    ***",
                "           ** ",
                "             **",
                "       *****   "
        });

        return patternMap;
    }
    public static void displayBanner(String message) {

        Map<Character, String[]> patternMap = buildCharacterPatternMap();

        int totalRows = 7;

        for (int row = 0; row < totalRows; row++) {

            StringBuilder lineBuilder = new StringBuilder();

            for (int i = 0; i < message.length(); i++) {

                char ch = message.charAt(i);
                String[] pattern = patternMap.get(ch);

                if (pattern != null) {
                    lineBuilder.append(pattern[row]);
                    lineBuilder.append("   ");
                }
            }

            System.out.println(lineBuilder.toString());
        }
    }


}
